# Generated by Django 4.2.5 on 2023-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='book',
            name='dest',
            field=models.CharField(choices=[('Kochi', 'Kochi'), ('Calicut', 'Calicut')], default='Calicut', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('Kochi', 'Kochi'), ('Calicut', 'Calicut')], default='Kochi', max_length=30),
        ),
    ]
