# Generated by Django 4.2.5 on 2023-09-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
