# Generated by Django 4.2.5 on 2023-09-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
